x/wasm refactoring - detaching the custom wasm proto part of lbm-sdk
line/lbm-sdk pull request #661
Opened 2022-09-05 06:22 UTC by zemyblue

## Description

closes: #623 

Apply the changes of #625 and #655 
* detaching `StoreCodeAndInstantiateContract from wasm's tx.proto
* add inactive contract management in wasm

## Motivation and context

## How has this been tested?

## Screenshots (if appropriate):

## Checklist:

- [ ] I followed the [contributing guidelines](https://github.com/line/lbm-sdk/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/line/lbm-sdk/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have added a relevant changelog to `CHANGELOG.md`
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated API documentation `client/docs/swagger-ui/swagger.yaml`

2022-09-05 08:52 UTC, 0Tech requested changes

2022-09-05 08:52 UTC, 0Tech commented on CHANGELOG.md
> +* (x/wasm) [\#661](https://github.com/line/lbm-sdk/pull/625) x/wasm refactoring - detaching the custom wasm proto part of lbm-sdk. (apply changes of [\#625](https://github.com/line/lbm-sdk/pull/625)
Mismatch in the PR numbers.
```suggestion
* (x/wasm) [\#661](https://github.com/line/lbm-sdk/pull/661) x/wasm refactoring - detaching the custom wasm proto part of lbm-sdk. (apply changes of [\#625](https://github.com/line/lbm-sdk/pull/625) and [\#655](https://github.com/line/lbm-sdk/pull/655))
```

2022-09-06 00:05 UTC, 0Tech approved these changes

2022-09-06 07:13 UTC, shiki-tak approved these changes

2022-09-06 07:18 UTC, loloicci approved these changes

2022-09-06 07:30 UTC, dudong2 approved these changes

2022-09-06 07:34 UTC, merged